net: sockets: Fix compilation of getaddrinfo()
If the user call getaddrinfo() while K_HEAP_MEM_POOL_SIZE == 0 and
CONFIG_NET_IP=y, he get a link time failure:

  .../ld.bfd: ...: in function `zsock_getaddrinfo':
  ...(.text.zsock_getaddrinfo+0xe): undefined reference to `k_calloc'

In fact, k_calloc() is required if CONFIG_NET_IP or CONFIG_DNS_RESOLVER is
set (because of the definition of ANY_RESOLVER) but K_HEAP_MEM_POOL_SIZE is
guaranteed to be != 0 only if CONFIG_DNS_RESOLVER is set.

So, forward the dependency in Kconfig to fix the issue.

Upstream-status: pr
Signed-off-by: Jérôme Pouiller <jerome.pouiller@silabs.com>
(cherry picked from commit bd89df270928feab916651b44a222bcb022f6f7e)